/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Users */
        get: operations["get_users_api_users__get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_users__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredients/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Ingredients */
        get: operations["search_ingredients_api_ingredients_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingredients */
        get: operations["get_ingredients_api_ingredients__get"];
        put?: never;
        /** Create Ingredient */
        post: operations["create_ingredient_api_ingredients__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredients/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Ingredient */
        patch: operations["update_ingredient_api_ingredients__item_id__patch"];
        trace?: never;
    };
    "/api/fridge/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fridge Items */
        get: operations["get_fridge_items_api_fridge__get"];
        put?: never;
        /** Create Fridge Item */
        post: operations["create_fridge_item_api_fridge__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fridge/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Fridge Item */
        delete: operations["delete_fridge_item_api_fridge__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Fridge Item */
        patch: operations["update_fridge_item_api_fridge__item_id__patch"];
        trace?: never;
    };
    "/api/condiments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Condiments */
        get: operations["get_condiments_api_condiments__get"];
        put?: never;
        /** Create Condiment */
        post: operations["create_condiment_api_condiments__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/condiments/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Condiment */
        delete: operations["delete_condiment_api_condiments__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Condiment */
        patch: operations["update_condiment_api_condiments__item_id__patch"];
        trace?: never;
    };
    "/api/favorites/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Favorites */
        get: operations["list_favorites_api_favorites__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Favorite */
        post: operations["add_favorite_api_favorites__recipe_id__post"];
        /** Remove Favorite */
        delete: operations["remove_favorite_api_favorites__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Recipes */
        get: operations["search_recipes_api_recipes__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_api_recipes__recipe_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipe/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest Menu */
        post: operations["suggest_menu_api_recipe_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipe/suggest/jobs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Suggest Job */
        get: operations["get_latest_suggest_job_api_recipe_suggest_jobs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipe/suggest/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suggest Job Status */
        get: operations["get_suggest_job_status_api_recipe_suggest_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipe/suggest/add-shopping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Shopping From Suggest */
        post: operations["add_shopping_from_suggest_api_recipe_suggest_add_shopping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shopping Items */
        get: operations["get_shopping_items_api_shopping__get"];
        put?: never;
        /** Create Shopping Item */
        post: operations["create_shopping_item_api_shopping__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping/{item_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Check Shopping Item */
        patch: operations["check_shopping_item_api_shopping__item_id__check_patch"];
        trace?: never;
    };
    "/api/shopping/by-name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Shopping Item By Name */
        post: operations["create_shopping_item_by_name_api_shopping_by_name_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Shopping Item */
        delete: operations["delete_shopping_item_api_shopping__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddShoppingParams */
        AddShoppingParams: {
            /** Ingredient Names */
            ingredient_names: string[];
        };
        /** CondimentCreateParams */
        CondimentCreateParams: {
            /** Name */
            name: string;
            /** @default full */
            quantity_status: components["schemas"]["QuantityStatus"];
            /**
             * Is Staple
             * @default true
             */
            is_staple: boolean;
        };
        /** CondimentResponse */
        CondimentResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Quantity Status */
            quantity_status: string;
            /** Is Staple */
            is_staple: boolean;
            /** Ingredient Master Id */
            ingredient_master_id: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CondimentUpdateParams */
        CondimentUpdateParams: {
            quantity_status: components["schemas"]["QuantityStatus"];
        };
        /** FridgeItemCreateParams */
        FridgeItemCreateParams: {
            /** Ingredient Master Id */
            ingredient_master_id: number;
            /** Expiry Date */
            expiry_date?: string | null;
            /** @default full */
            quantity_status: components["schemas"]["QuantityStatus"];
        };
        /** FridgeItemResponse */
        FridgeItemResponse: {
            /** Id */
            id: number;
            /** Ingredient Master Id */
            ingredient_master_id: number;
            /** Ingredient Name */
            ingredient_name: string;
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /** Quantity Status */
            quantity_status: string;
            /** Is Staple */
            is_staple: boolean;
            /**
             * Registered At
             * Format: date-time
             */
            registered_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FridgeItemUpdateParams */
        FridgeItemUpdateParams: {
            quantity_status: components["schemas"]["QuantityStatus"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngredientMasterCreateParams */
        IngredientMasterCreateParams: {
            /** Name */
            name: string;
            /** Default Expiry Days */
            default_expiry_days: number;
            /**
             * Is Staple
             * @default false
             */
            is_staple: boolean;
            /**
             * Category
             * @default ingredient
             */
            category: string;
        };
        /** IngredientMasterResponse */
        IngredientMasterResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Default Expiry Days */
            default_expiry_days: number;
            /** Is Staple */
            is_staple: boolean;
            /** Category */
            category: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** IngredientMasterUpdateParams */
        IngredientMasterUpdateParams: {
            /** Default Expiry Days */
            default_expiry_days?: number | null;
            /** Is Staple */
            is_staple?: boolean | null;
        };
        /**
         * QuantityStatus
         * @enum {string}
         */
        QuantityStatus: "full" | "half" | "little";
        /** RecipeDetailResponse */
        RecipeDetailResponse: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Menu Num */
            menu_num: string | null;
            /** Image Url */
            image_url: string | null;
            /** Source Url */
            source_url: string;
            /** Ingredients */
            ingredients: components["schemas"]["RecipeIngredientResponse"][];
            /** Materials */
            materials: components["schemas"]["RecipeMaterialResponse"][];
            /** Steps */
            steps: components["schemas"]["RecipeStepResponse"][];
        };
        /** RecipeIngredientResponse */
        RecipeIngredientResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** RecipeListResponse */
        RecipeListResponse: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Menu Num */
            menu_num: string | null;
            /** Image Url */
            image_url: string | null;
            /** Ingredient Names */
            ingredient_names: string[];
        };
        /** RecipeMaterialResponse */
        RecipeMaterialResponse: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: string | null;
            /** Group Name */
            group_name: string | null;
        };
        /** RecipeStepResponse */
        RecipeStepResponse: {
            /** Step Order */
            step_order: number;
            /** Text */
            text: string;
        };
        /** ShoppingItemCreateByNameParams */
        ShoppingItemCreateByNameParams: {
            /** Name */
            name: string;
            /** @default manual */
            source: components["schemas"]["ShoppingSource"];
        };
        /** ShoppingItemCreateParams */
        ShoppingItemCreateParams: {
            /** Ingredient Master Id */
            ingredient_master_id: number;
            /** @default manual */
            source: components["schemas"]["ShoppingSource"];
        };
        /** ShoppingItemResponse */
        ShoppingItemResponse: {
            /** Id */
            id: number;
            /** Ingredient Master Id */
            ingredient_master_id: number;
            /** Ingredient Name */
            ingredient_name: string;
            /** Source */
            source: string;
            /** Is Checked */
            is_checked: boolean;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Checked At */
            checked_at: string | null;
        };
        /**
         * ShoppingSource
         * @enum {string}
         */
        ShoppingSource: "manual" | "recipe" | "staple_auto";
        /** SuggestJobCreateResponse */
        SuggestJobCreateResponse: {
            /** Job Id */
            job_id: number;
        };
        /** SuggestJobStatusResponse */
        SuggestJobStatusResponse: {
            /** Job Id */
            job_id: number;
            /** Status */
            status: string;
            /** Suggestions */
            suggestions?: components["schemas"]["SuggestedRecipeResponse"][] | null;
            /** Error */
            error?: string | null;
        };
        /** SuggestParams */
        SuggestParams: {
            /**
             * Mode
             * @default omakase
             */
            mode: string;
            /**
             * Ingredient Master Ids
             * @default []
             */
            ingredient_master_ids: number[];
        };
        /** SuggestedMaterialResponse */
        SuggestedMaterialResponse: {
            /** Name */
            name: string;
            /** Quantity */
            quantity?: string | null;
            /** Group Name */
            group_name?: string | null;
        };
        /** SuggestedRecipeResponse */
        SuggestedRecipeResponse: {
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Recipe Id */
            recipe_id?: number | null;
            /** Menu Num */
            menu_num?: string | null;
            /** Image Url */
            image_url?: string | null;
            /**
             * Category
             * @default
             */
            category: string;
            /** Used Ingredients */
            used_ingredients: string[];
            /**
             * Missing Ingredients
             * @default []
             */
            missing_ingredients: string[];
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["SuggestedStepResponse"][];
            /**
             * Materials
             * @default []
             */
            materials: components["schemas"]["SuggestedMaterialResponse"][];
            /** Manual Mode */
            manual_mode?: string | null;
            /** Manual Stir */
            manual_stir?: string | null;
            /** Manual Time Min */
            manual_time_min?: number | null;
        };
        /** SuggestedStepResponse */
        SuggestedStepResponse: {
            /** Step Order */
            step_order: number;
            /** Text */
            text: string;
        };
        /** UserCreateParams */
        UserCreateParams: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_users_api_users__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    create_user_api_users__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_ingredients_api_ingredients_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingredients_api_ingredients__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientMasterResponse"][];
                };
            };
        };
    };
    create_ingredient_api_ingredients__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientMasterCreateParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientMasterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ingredient_api_ingredients__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientMasterUpdateParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientMasterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fridge_items_api_fridge__get: {
        parameters: {
            query?: {
                /** @description 食材名で検索 */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FridgeItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_fridge_item_api_fridge__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FridgeItemCreateParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FridgeItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_fridge_item_api_fridge__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_fridge_item_api_fridge__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FridgeItemUpdateParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FridgeItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_condiments_api_condiments__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CondimentResponse"][];
                };
            };
        };
    };
    create_condiment_api_condiments__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CondimentCreateParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CondimentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_condiment_api_condiments__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_condiment_api_condiments__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CondimentUpdateParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CondimentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favorites_api_favorites__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
        };
    };
    add_favorite_api_favorites__recipe_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favorite_api_favorites__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_recipes_api_recipes__get: {
        parameters: {
            query?: {
                /** @description 料理名または食材名で検索 */
                q?: string;
                /** @description お気に入りのみ表示 */
                favorites_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeListResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_api_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_menu_api_recipe_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestJobCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_suggest_job_api_recipe_suggest_jobs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestJobStatusResponse"] | null;
                };
            };
        };
    };
    get_suggest_job_status_api_recipe_suggest_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestJobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_shopping_from_suggest_api_recipe_suggest_add_shopping_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddShoppingParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shopping_items_api_shopping__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingItemResponse"][];
                };
            };
        };
    };
    create_shopping_item_api_shopping__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShoppingItemCreateParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_shopping_item_api_shopping__item_id__check_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_shopping_item_by_name_api_shopping_by_name_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShoppingItemCreateByNameParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_shopping_item_api_shopping__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
