"""add_category_to_hotcook_recipes

Revision ID: ce5310224b1b
Revises: 2f0f59a7226b
Create Date: 2026-03-08 15:41:41.757454

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce5310224b1b"
down_revision: str | Sequence[str] | None = "2f0f59a7226b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hotcook_recipes", sa.Column("category", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hotcook_recipes", "category")
    # ### end Alembic commands ###
